### ISSUE TITLE
Temperature is wrong after acpi_call update

### ISSUE THREAD

**Issue by SingingFrog7** [s-h-a-d-o-w/alfc#1]
Hello

I accidentally update acpi-call by installing acpi-call package on my computer (debian). ~~Since then, the tempeture read by your app is missing the decimal point, so it sees a temperature like 600 instead of 60.0~~

~~Because of that, the fan is always at 100%. If i try to set threshold to higher than 100, I have an error.~~ SEE NEXT POST

I tried removing (and purging) acpi-call and re-installing from your last release without success, it always show the same. ~~I tried to modify alfc.config.json to manually set the numbers like 600 or 800, but it didn't work either.~~

~~I'm not sure what to do or how to revert acpi-call to the previous version~~

Thanks for your help

Note: Everything was working fine before. My computer is a 15G XC, running Debian stable

**Comment by SingingFrog7** [comment]
I was finally able to overide the 100 limit, but it seems that the numbers are not exactly the temperature (in comparison to `sensors` and the `/sys/class/thermal/` file at least)
It does burst when the CPU is used but it go over 1000 for a second or two while sensors show a burst aroung 67~72°C

I builded apci_call from source and have the same result

For example, the frontend show:
```
CPU: 682°C
GPU: 650°C
```
Result of `sensors` a the same time:
```
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +41.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +38.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +38.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +37.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +37.0°C  (high = +100.0°C, crit = +100.0°C)
Core 6:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 7:        +38.0°C  (high = +100.0°C, crit = +100.0°C)

nvme-pci-0600
Adapter: PCI adapter
Composite:    +24.9°C  (low  =  -5.2°C, high = +83.8°C)
                       (crit = +87.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +119.0°C)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +34.0°C  

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +43.0°C  

BAT1-acpi-0
Adapter: ACPI interface
in0:          16.86 V  
curr1:         0.00 A  

nvme-pci-0500
Adapter: PCI adapter
Composite:    +25.9°C  (low  = -20.1°C, high = +74.8°C)
                       (crit = +79.8°C)
```

Any idea?

**Comment by s-h-a-d-o-w** [comment]
Might be a naive question but... what's the model of your laptop?

**Comment by SingingFrog7** [comment]
Sorry, I didn't give the complete model, it's an Aorus 15G XC

**Comment by s-h-a-d-o-w** [comment]
Actually, I suppose it doesn't matter, since everything worked fine before.

Well, I'm afraid you'd either have to debug for yourself what the difference between the two acpi-call versions is or ask on some Linux forum or SO how to actually roll this back on Debian.
The former would of course be a better solution long-term. I'm also wondering what the reason for a breaking change in that tool was. If you can find something, I'd appreciate it if you'd share it here!

**Comment by s-h-a-d-o-w** [comment]
Did a fresh install with the [latest acpi_call](https://github.com/nix-community/acpi_call) just before and encountered no issues, so I'm closing this.
