### ISSUE TITLE
IntelOverclockingSDK.dll issue

### ISSUE THREAD

**Issue by nikitavedre** [s-h-a-d-o-w/alfc#12]
Is there any dependency to use IntelOverclockingSDK.dll? To  use  IntelOverclockingSDK.dll should I install intel Extreme utility?

**Comment by s-h-a-d-o-w** [comment]
Depends.

On Windows 11, changing power limits simply doesn't work.

On Windows 10, the Gigabyte control center includes XTU. If you don't have that installed or want to remove it, see instructions here: https://github.com/s-h-a-d-o-w/alfc#getting-rid-of-gigabyte-control-center

**Comment by nikitavedre** [comment]
I have observed that when I uninstalled XTU ,IntelOverclockingSDK.dll  function giving error "System.NullReferenceException 
  Message=Object reference not set to an instance of an object." why is  this thing happening?

**Comment by s-h-a-d-o-w** [comment]
I unfortunately don't know more than I've just told you.
If you figure something out, please let us know.
