### ISSUE TITLE
The program fails to run if its in a directory with a space (on Windows 11)

### ISSUE THREAD

**Issue by StealthDragonJ** [s-h-a-d-o-w/alfc#13]
If there is a space in the directory path (i.e. folder name has a space in it) running the run.bat file does nothing and trying to run the install.bat file creates this error...
![alfc v1 1 0 directory error](https://github.com/s-h-a-d-o-w/alfc/assets/62991571/436a9970-da71-4c48-86fb-63223eaa189f)

Found while using a Gigabyte Aero Classic SA on Windows 11 using PowerShell but may be applicable else where as well

**Comment by s-h-a-d-o-w** [comment]
Thanks for making me aware of this!
Works now with the latest release.

![Capture](https://github.com/s-h-a-d-o-w/alfc/assets/16936908/bb05f3e6-0e02-499b-91d9-dcaaf7004ded)
