### ISSUE TITLE
Pressing the minus button in the UI can break the fan controls

### ISSUE THREAD

**Issue by StealthDragonJ** [s-h-a-d-o-w/alfc#15]
If you press the minus button when there is only one row left you end up with no more rows and you get stuck with no plus buttons to set the fan controls...

E.g. here I kept pressing minus on the GPU section of the fan controls and now I cannot add any fan controls based on the GPU temp
![alfc v1 1 1 minus button issue](https://github.com/s-h-a-d-o-w/alfc/assets/62991571/b3e31a13-8e6a-4bcd-a33e-a58113cddea2)

The only workaround I have found is to get a new copy of the program so that the values are reset to default

**Comment by s-h-a-d-o-w** [comment]
Thanks for reporting this, fixed.
