### ISSUE TITLE
Suggestion to Add Battery Charging Threshold Control

### ISSUE THREAD

**Issue by Ixmoon** [s-h-a-d-o-w/alfc#20]
Thank you very much for your dedication to this project. It has been extremely helpful to me. Following your guidance, I implemented a way to control the battery charging threshold with code. I've tested it on an Aorus 15P XD, but I'm unsure if it works on other models.

Initially, I wanted to modify this project to add this feature, but I wasn't sure where to start. As a result, I created a standalone Windows application to accomplish this, which is available on GitHub for reference: [Gigabyte Aorus Battery Manager](https://github.com/lxmoonlily/Gigabyte-Aorus-Battery-Manager).

Here’s the command-line version of the code I used for testing, which might be helpful if you’d consider incorporating this functionality into the project:

```csharp
using System;
using ComHeader;
using SmartManager;

namespace BatteryChargeControl
{
    // Enum to define charge policies
    enum ChargePolicy
    {
        Standard = 0, // Standard charge policy
        Custom = 4    // Custom charge policy
    }

    class Program
    {
        static void Main(string[] args)
        {
            while (true)
            {
                uint chargeStopStatus = 0; // Variable to store charge stop threshold
                uint chargePolicy = 0;     // Variable to store charge policy

                GetChargeStop(ref chargeStopStatus);   // Retrieve current charge stop threshold
                GetChargePolicy(ref chargePolicy);     // Retrieve current charge policy

                DisplayCurrentSettings(chargeStopStatus, (ChargePolicy)chargePolicy);

                Console.WriteLine("Please enter charge policy (standard or custom), or type 'exit' to quit, or any other key to skip:");
                string input = Console.ReadLine().ToLower();

                if (input == "exit") break;

                switch (input)
                {
                    case "standard":
                        SetChargePolicy((int)ChargePolicy.Standard); // Set policy to Standard
                        break;
                    case "custom":
                        SetChargePolicy((int)ChargePolicy.Custom);   // Set policy to Custom
                        break;
                    default:
                        Console.WriteLine("Skipping charge policy setting...");
                        break;
                }

                Console.WriteLine("Please enter custom charge threshold (0-100), or type 'exit' to quit:");
                input = Console.ReadLine().ToLower();

                if (input == "exit") break;

                if (int.TryParse(input, out int newThreshold) && newThreshold >= 0 && newThreshold <= 100)
                {
                    SetChargeStop(newThreshold); // Set new charge stop threshold
                    Console.WriteLine($"Charge threshold updated to: {newThreshold}");
                }
                else
                {
                    Console.WriteLine("Invalid input, please enter a number between 0 and 100.");
                }

                GetChargeStop(ref chargeStopStatus);   // Refresh charge stop threshold
                GetChargePolicy(ref chargePolicy);     // Refresh charge policy

                DisplayCurrentSettings(chargeStopStatus, (ChargePolicy)chargePolicy);

                Console.WriteLine("Press any key to continue, or 'exit' to quit...");
                if (Console.ReadLine().ToLower() == "exit") break;
            }
        }

        // Display current charge settings
        private static void DisplayCurrentSettings(uint chargeStop, ChargePolicy chargePolicy)
        {
            Console.WriteLine($"Current charge threshold: {chargeStop}");
            Console.WriteLine("Current charge policy: " + (chargePolicy == ChargePolicy.Custom ? "Custom" : "Standard"));
        }

        // Set charge stop threshold
        private static void SetChargeStop(int iVal)
        {
            CWMI cWMI = new CWMI();
            WMI_ARGS[] args = { new WMI_ARGS { DataType = "Data", value = iVal } };
            cWMI.CallMethod("ROOT\\WMI", "GB_WMIACPI_Set", "SetChargeStop", args);
        }

        // Set charge policy
        private static void SetChargePolicy(int iVal)
        {
            CWMI cWMI = new CWMI();
            WMI_ARGS[] args = { new WMI_ARGS { DataType = "Data", value = iVal } };
            cWMI.CallMethod("ROOT\\WMI", "GB_WMIACPI_Set", "SetChargePolicy", args);
        }

        // Get current charge stop threshold
        private static void GetChargeStop(ref uint uiVal)
        {
            CWMI cWMI = new CWMI();
            uiVal = cWMI.GetWMIData("ROOT\\WMI", "GB_WMIACPI_Get", "GetChargeStop");
        }

        // Get current charge policy
        private static void GetChargePolicy(ref uint uiVal)
        {
            CWMI cWMI = new CWMI();
            uiVal = cWMI.GetWMIData("ROOT\\WMI", "GB_WMIACPI_Get", "GetChargePolicy");
        }
    }
}
```

I hope this example can assist in adding similar functionality to this project. Thanks again for your incredible work!

**Comment by s-h-a-d-o-w** [comment]
That's awesome to hear that I helped you figure that out!

Sounds like a great little tool too! Unfortunately, I can't try it out because my battery bloated like two years ago. I removed it and have the laptop plugged in permanently ever since. 😄

I think it actually makes sense to maintain these tools separately and for people to just use whatever they need. Maintaining an all in one solution would be tougher. If there was a large modding community with lots of users, it could make sense but I think for the time being, it makes more sense to have small, separate tools.

But it does makes sense to collaborate to some degree - which is why I've added a link to your tool in the README [here](https://github.com/s-h-a-d-o-w/alfc?tab=readme-ov-file#other-tools-for-aorus-laptops). After all, if my battery hadn't died, I would totally use it!

> I've tested it on an Aorus 15P XD, but I'm unsure if it works on other models.

I would recommend mentioning that somewhere in your README and inviting people to confirm whether it works for them on different models. 🙂 (Alternatively - maybe dig around the decompiled driver a bit more to gain confidence? Because as far as I recall, it was very easy for me to tell that the GPU boost is highly device dependent - lots of `if` statements for different models, ending up with different commands or addresses. If you don't see anything like that, I think it's fair to assume that charging threshold control works the same way on all Aorus models.)

**Comment by Ixmoon** [comment]
Thank you so much for your kind words and support! I'm glad to hear that my work could contribute to this project, and I really appreciate the feedback and insights.

I'm sorry to hear about your battery bloating! (Maybe if my tool had come out a little sooner, it could've helped prevent that😄)

I think you’re right about maintaining separate tools for simplicity, especially without a larger community to support a comprehensive solution. Thanks for adding the link to my tool in the README—it’ll definitely help anyone interested in managing battery charging thresholds more easily!

Just to note, I believe the code should work independently of the battery itself, so it should still function even with your battery removed. If you’re open to trying it out, feel free to give it a shot!

Regarding the compatibility across different models, I agree with your points. I wouldn't expect Gigabyte to have modified the Set/GetChargeStop functionality, as it’s simply setting a threshold value. But with Set/GetChargePolicy, there may be some variation: on my model, 0 and 4 represent the standard and custom charge control options in the control center. However, on other models, the custom value might not be 4—it could be 3 or 5 instead, which would prevent my tool from working correctly.

I'll update the README to note that compatibility is tested on the Aorus 15P XD and invite feedback from users with other models. I’ll also take a closer look at the driver code to see if there are any specific model variations that might affect the policy values.

Thanks again for the thoughtful feedback—I'm glad to collaborate in any way that supports this community!

**Comment by s-h-a-d-o-w** [comment]
> I believe the code should work independently of the battery itself, so it should still function even with your battery removed. If you’re open to trying it out, feel free to give it a shot!

I would be but don't see a point in doing so, since it wouldn't do anything and I wouldn't be able to validate that it works.

> Thanks again for the thoughtful feedback—I'm glad to collaborate in any way that supports this community!

Sure thing!
