### ISSUE TITLE
alfc works on Aorus 17YC (30 series)

### ISSUE THREAD

**Issue by morialo3** [s-h-a-d-o-w/alfc#8]
Just reporting the status of support for this laptop, many thanks
one thing to add, the repo provided "acpi_call-dkms" makes alfc works as intended, no workarounds needed.
Distro: Manjaro - linux kernel:5.18rc7

**Comment by morialo3** [comment]
Noticed one thing, a "Warning" in systemctl, not fatal or anything:
`systemctl status alfc                                                                                                                                                                                                             
● alfc.service - alfc
     Loaded: loaded (/usr/lib/systemd/system/alfc.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2022-05-22 15:20:20 +04; 2h 5min ago
   Main PID: 795 (node)
      Tasks: 11 (limit: 38339)
     Memory: 84.4M
        CPU: 13min 55.201s
     CGroup: /system.slice/alfc.service
             └─ 795 /usr/bin/node /home/amro/Downloads/PortableAPP/alfc run

Warning: some journal files were not opened due to insufficient permissions`

maybe suggest a permission for files/services, so users can see if everything is applied on-boot/live modification, or there some setting not applied

**Comment by morialo3** [comment]
Looks like `Systemd` having some issues with `alfc.service`

> sudo systemctl status alfc
[sudo] password for XXXX:
× alfc.service - alfc
     Loaded: loaded (/usr/lib/systemd/system/alfc.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2022-05-25 15:51:26 +04; 25s ago
   Duration: 1.026s
    Process: 749 ExecStart=/usr/bin/node /home/XXXX/Downloads/PortableAPP/alfc run (code=exited, status=1/FAILURE)
   Main PID: 749 (code=exited, status=1/FAILURE)
        CPU: 813ms
May 25 15:51:25 XXXX-aorus17gyc systemd[1]: Started alfc.
May 25 15:51:26 XXXX-aorus17gyc systemd[1]: alfc.service: Main process exited, code=exited, status=1/FAILURE
May 25 15:51:26 XXXX-aorus17gyc systemd[1]: alfc.service: Failed with result 'exit-code'.

> sudo systemctl start alfc

> sudo systemctl status alfc
● alfc.service - alfc
     Loaded: loaded (/usr/lib/systemd/system/alfc.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2022-05-25 15:52:20 +04; 37s ago
   Main PID: 1820 (node)
      Tasks: 12 (limit: 38339)
     Memory: 21.9M
        CPU: 6.454s
     CGroup: /system.slice/alfc.service
             ├─1820 /usr/bin/node /home/XXXX/Downloads/PortableAPP/alfc run
             ├─3214 /bin/sh -c "echo '\\_SB.PCI0.AMW0.WMBC 0 0xe3 0' | tee /proc/acpi/call > /dev/null && cat /proc/acpi/call"
             └─3217 tee /proc/acpi/call
May 25 15:52:20 XXXX-aorus17gyc systemd[1]: Started alfc.

as a workaround -for now- I added this line: `Restart=on-failure` to `alfc.service` , this should do the trick.

**Comment by s-h-a-d-o-w** [comment]
> no workarounds needed

Installing acpi_call from source is not a workaround but is done for increased likelihood that it remains compatible over time, since people [have had problems with other versions of it in the past](https://github.com/s-h-a-d-o-w/alfc/issues/1).

> Looks like Systemd having some issues with alfc.service

I doubt that that's a problem with systemd, given that I and others have used alfc successfully with it for many months.

It's been a year or two since I needed to debug the service on Linux and I don't remember how. But one thing is clear - Node always provides some sort of message when crashing. While it's not in the log that you shared, there's gotta be some way to get to it.
Aside from that, you could always try to install acpi_call from source as an attempt that isn't as time intensive.

**Comment by morialo3** [comment]
> you could always try to install acpi_call from source as an attempt that isn't as time intensive.

I`ll try your acpi from the instructions page, and report. Thanks for the reply.

EDIT: 
So I went and did everything from the beginning, uninstall and then reinstall `alfc`,  installed [acpi_call](https://github.com/nix-community/acpi_call) as recommended, moved the app to more privileged location `/opt`. here the output for `./install.sh`:

     (node:20490) [DEP0128] DeprecationWarning: Invalid 'main' field in 
     '/opt/alfc/package.json' of 'index.ts'. Please either fix that or report it to the module author
     (Use `node --trace-deprecation ...` to show where the warning was created)
     Error: Command failed: cd "/opt/alfc"; "/usr/bin/pkexec" --disable-internal-agent 
     /bin/bash -c "echo SUDOPROMPT; node /opt/alfc install-as-sudo"
     (node:20501) [DEP0128] DeprecationWarning: Invalid 'main' field in 
     '/opt/alfc/package.json' of 'index.ts'. Please either fix that or report it to the module author
      (Use `node --trace-deprecation ...` to show where the warning was created) /opt/alfc/index.js:4357
      throw error;
    ^
  
     Error: Command failed: service alfc start
    /bin/sh: line 1: service: command not found

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12) {
    code: 127,
    killed: false,
    signal: null,
    cmd: 'service alfc start'
    }
    Node.js v18.2.0

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
    code: 1,
    killed: false,
    signal: null,
    cmd: 'cd "/opt/alfc"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo 
    SUDOPROMPT; node /opt/alfc install-as-sudo"'
    }

then `sudo systemctl status alfc`  immediately shows this:

>  ● alfc.service - alfc
     Loaded: loaded (/usr/lib/systemd/system/alfc.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2022-05-29 01:07:03 +04; 30s ago
   Main PID: 1720697 (node)
      Tasks: 11 (limit: 38339)
     Memory: 21.4M
        CPU: 1.617s
     CGroup: /system.slice/alfc.service
             └─1720697 /usr/bin/node /home/amro/Downloads/PortableAPP/alfc run
May 29 01:07:03 xxxx-aorus17gyc systemd[1]: Started alfc.
May 29 01:07:22 xxxx-aorus17gyc systemd[1]: /usr/lib/systemd/system/alfc.service:4: Failed to add dependency on acpi_call, ignoring: Invalid argument

on reboot `sudo systemctl status alfc` 

> × alfc.service - alfc
     Loaded: loaded (/usr/lib/systemd/system/alfc.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2022-05-29 15:01:08 +04; 43s ago
   Duration: 968ms
    Process: 718 ExecStart=/usr/bin/node /opt/alfc run (code=exited, status=1/FAILURE)
   Main PID: 718 (code=exited, status=1/FAILURE)
        CPU: 775ms
May 29 15:01:07 xxxx-aorus17gyc systemd[1]: Started alfc.
May 29 15:01:08 xxxx-aorus17gyc systemd[1]: alfc.service: Main process exited, code=exited, status=1/FAILURE
May 29 15:01:08 xxxx-aorus17gyc systemd[1]: alfc.service: Failed with result 'exit-code'.

Tell me what do you think.

**Comment by morialo3** [comment]
Closing not an issue.

**Comment by s-h-a-d-o-w** [comment]
Glad to hear that you were able to work it out!

**Comment by morialo3** [comment]
> Glad to hear that you were able to work it out!

Thanks alot, it's hard to find any support for laptops fan control, or laptops in Linux in general, thanks again.
